apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: 14.11.0
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    server:
      # ingress:
      #   enabled: true
      #   hosts:
      #   - prometheus.fener.net
      persistentVolume:
        storageClass: nfs-client
      service:
        annotations: 
          linkerd.io/inject: enabled
    alertmanager:
      persistentVolume:
        storageClass: nfs-client
      service:
        annotations: 
          linkerd.io/inject: enabled
    nodeExporter:
      service:
        annotations: 
          linkerd.io/inject: enabled
    pushgateway:
      service:
        annotations: 
          prometheus.io/probe: pushgateway
          linkerd.io/inject: enabled
    
    
