apiVersion: v1
kind: Namespace
metadata:
  name: linkered-viz
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
