apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: flux-user
spec:
  chart:
    spec:
      chart: drone
      sourceRef:
        kind: HelmRepository
        name: drone
      version: 0.1.7
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      hosts:
        - host: drone.fener.net
          paths:
            - "/"
    persistentVolume:
      storageClass: nfs-client
    env:
      DRONE_SERVER_HOST: drone.fener.net
      DRONE_RPC_SECRET: 9gcMePY7@hzsnJ
      DRONE_GITEA_CLIENT_ID: c64c8211-b3f1-4628-886d-d6e870366bc6
      DRONE_GITEA_CLIENT_SECRET: uoGmv3JUNNzLh1fjdDcosfpmRTmUKOMEJ3-UOnXM54o=
      DRONE_GITEA_SERVER: http://gitea.fener.net