apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-user
spec:
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
      version: 4.0.3
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      hosts:
      - host: gitea.fener.net
        paths:
          - path: /
            pathType: Prefix
    persistence:
      storageClass: nfs-client
    memcached:
      image:
        repository: memcached
        tag: 1.6.9
      persistence:
        enabled: true
        storageClass: nfs-client
      arguments:
        - memcached
    postgresql:
      image:
        repository: postgres
        tag: 11.2
      persistence:
        storageClass: nfs-client
