apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry-proxy
  namespace: flux-user
spec:
  chart:
    spec:
      chart: docker-registry
      sourceRef:
        kind: HelmRepository
        name: twuni
      version: 1.11.0
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      storageClass: nfs-client
    proxy:
      enabled: true
      remoteurl: https://registry-1.docker.io
    ingress:
      enabled: true
      hosts:
        - proxy.registry.fener.net
  valuesFrom:
  - kind: Secret
    name: docker-hub-creds
    valuesKey: username
    targetPath: proxy.username
  - kind: Secret
    name: docker-hub-creds
    valuesKey: password
    targetPath: proxy.password 