apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-user
spec:
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      version: 2.6.5
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
    nextcloud:
      host: nextcloud.fener.net
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgres-postgresql
      user: nextcloud
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-secret
        passwordKey: postgresql-password
        usernameKey: user
    presistence:
      enabled: true
      storageClass: nfs-client

