apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-postgres
  namespace: flux-user
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 10.5.1
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullNameOverride: nextcloud-postgres
    enabled: true
    image:
      repository: postgres
      tag: 11.2
      persistence:
        storageClass: nfs-client
    persistence:
      mountPath: /var/lib/postgresql
      storageClass: nfs-client
    postgresqlDataDir: /var/lib/postgresql/data/pgdata
    postgresqlUsername: nextcloud
    postgresqlDatabase: nextcloud
    existingSecret: nextcloud-db-secret
