apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: flux-user
spec:
  chart:
    spec:
      chart: bitwardenrs
      sourceRef:
        kind: HelmRepository
        name: gissilabs
      version: 0.3.0
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      host: bitwarden.fener.net
    service:
      type: LoadBalancer
      httpPort: 3000
