apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-user
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: codecentric
      version: 11.0.0
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      storageClass: nfs-client
    image:
      repository: alemairebe/keycloak
      tag: 12.0.4
    postgresql:
      enabled: true
      image:
        repository: postgres
        tag: 11.12
    ingress:
      enabled: true
      rules:
      - host: keycloak.fener.net
        paths:
        - /
    extraEnv: |
      - name: KEYCLOAK_USER
        value: admin
      - name: KEYCLOAK_PASSWORD
        value: admin
