apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-user
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: 13.8.0
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    server:
      ingress:
        enabled: true
        hosts:
        - prometheus.fener.net
      persistence:
        storageClass: nfs-client
    alertmanager:
      persistence:
        storageClass: nfs-client
    
